apiVersion: v1
kind: Pod
metadata:
  name: perf-analyzer
  namespace: inference
spec:
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"

  containers:
    - name: perf-analyzer
      image: nvcr.io/nvidia/tritonserver:25.08-py3-sdk
      command:
        - sleep
        - "3600"
