apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton
  namespace: default
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: triton

  namespaceSelector:
    matchNames:
      - inference

  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics